// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB97Hh8lW43mEf0WNmuKCs6g0nx0K9WyH0',
    appId: '1:300224259247:web:6554c41a636b8563fce05a',
    messagingSenderId: '300224259247',
    projectId: 'skill-harvest-105d3',
    authDomain: 'skill-harvest-105d3.firebaseapp.com',
    storageBucket: 'skill-harvest-105d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMEll6Py9aOv2aD_IcoJkd0lro2zru2cA',
    appId: '1:300224259247:android:078a3e16d5f1fa6afce05a',
    messagingSenderId: '300224259247',
    projectId: 'skill-harvest-105d3',
    storageBucket: 'skill-harvest-105d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvB7q7jXDiIDQEfGRlTkNDfGSfmrb9LXk',
    appId: '1:300224259247:ios:4399cab2f4dc5fcbfce05a',
    messagingSenderId: '300224259247',
    projectId: 'skill-harvest-105d3',
    storageBucket: 'skill-harvest-105d3.appspot.com',
    iosBundleId: 'com.example.skillharvest',
  );
}
